[[events]]
type = "CREATE"
method = "PUT"
uri = "output/banzai/banzai.txt"
infile = "files/bible.txt"
id = 1

[[events]]
type = "SEND_LINE"
id = 1

[[events]]
type = "SEND_HEADERS"
id = 1

[[events]]
type = "SEND_BODY"
size = 2023696
id = 1

[[events]]
type = "CREATE"
method = "GET"
uri = "output/banzai/banzai.txt"
id = 2

[[events]]
type = "SEND_ALL"
id = 2

[[events]]
type = "WAIT"
id = 2

[[events]]
type = "SEND_BODY"
id = 1

[[events]]
type = "WAIT"
id = 1
