[[events]]
type = "CREATE"
method = "APPEND"
uri = "tests/borg.txt"
infile = "tests/test2.txt"
id = 1

[[events]]
type = "SEND_LINE"
id = 1

[[events]]
type = "SEND_HEADERS"
id = 1

[[events]]
type = "SEND_BODY"
size = 500
id = 1

[[events]]
type = "CREATE"
method = "GET"
uri = "tests/borg.txt"
id = 2

[[events]]
type = "SEND_ALL"
id = 2

[[events]]
type = "WAIT"
id = 2

[[events]]
type = "SEND_BODY"
id = 1

[[events]]
type = "WAIT"
id = 1
