# Create request 1 (R1): PUT the contents of `files/bible.txt` to `bible.txt`.
[[events]]
type = "CREATE"
method = "PUT"
uri = "tests/example.txt"
infile= "tests/test7.txt"
id = 1

# Send R1's request line.
[[events]]
type = "SEND_LINE"
id = 1

# Only begins once R2 has finished.
# Send R1's request headers.
[[events]]
type = "SEND_HEADERS"
id = 1

# Create request 2 (R2) and send entirety, then wait to for a response.
[[events]]
type = "CREATE"
method = "GET"
uri = "tests/test7.txt"
id = 2

# Send entirety of R2.
[[events]]
type = "SEND_ALL"
id = 2

# Wait for R2 to complete.
[[events]]
type = "WAIT"
id = 2


# Send R1's message body.
[[events]]
type = "SEND_BODY"
id = 1

# Wait for R1 to complete.
[[events]]
type = "WAIT"
id = 1