[[events]]
type = "CREATE"
method = "PUT"
uri = "output/lederberg/lederberg_1.txt"
infile = "files/bible.txt"
id = 1

[[events]]
type = "CREATE"
method = "PUT"
uri = "output/lederberg/lederberg_2.txt"
infile = "files/aaa.txt"
id = 2

[[events]]
type = "CREATE"
method = "GET"
uri = "files/bible.txt"
id = 3

[[events]]
type = "CREATE"
method = "GET"
uri = "files/aaa.txt"
id = 4

[[events]]
type = "SEND_ALL"
id = 2

[[events]]
type = "SEND_ALL"
id = 3

[[events]]
type = "SEND_ALL"
id = 4

[[events]]
type = "WAIT"
id = 2

[[events]]
type = "WAIT"
id = 3

[[events]]
type = "WAIT"
id = 4

[[events]]
type = "SEND_ALL"
id = 1

[[events]]
type = "WAIT"
id = 1
