# Test 4: 
# Start the server with two threads, start one request, but do not send
# any data.  Send three full requests, then finally send the data for
# the first request.  Ensure that the server produces correct output.

# Start R1, don't send anything.
[[events]]
type = "CREATE"
method = "GET"
uri = "bible.txt"
id = 1

# Send three entire requests and wait for them to finish.
[[events]]
type = "CREATE"
method = "PUT"
uri = "aaa.txt"
infile= "files/aaa.txt"
id = 2

[[events]]
type = "CREATE"
method = "PUT"
uri = "bible.txt"
infile= "files/bible.txt"
id = 3

[[events]]
type = "CREATE"
method = "GET"
uri = "README.md"
id = 4

[[events]]
type = "SEND_ALL"
id = 2

[[events]]
type = "SEND_ALL"
id = 3

[[events]]
type = "SEND_ALL"
id = 4

# Wait for them to finish.
[[events]]
type = "WAIT"
id = 2

[[events]]
type = "WAIT"
id = 3

[[events]]
type = "WAIT"
id = 4

# Finish sending R1.
[[events]]
type = "SEND_ALL"
id = 1

[[events]]
type = "WAIT"
id = 1