# Create request 1 (R1): PUT the contents of `files/bible.txt` to `bible.txt`.
[[events]]
type = "CREATE"
method = "PUT"
uri = "bible.txt"
infile= "files/bible.txt"
id = 1

# Send R1's request line.
[[events]]
type = "SEND_LINE"
id = 1

# Send R1's request headers.
[[events]]
type = "SEND_HEADERS"
id = 1

# Create request 2 (R2): GET the contents of `bible.txt`.
[[events]]
type = "CREATE"
method = "PUT"
uri = "foo.txt"
infile= "tests/test1.txt"
id = 2


# Send R2's request line.
[[events]]
type = "SEND_LINE"
id = 2

# Send R2's request headers.
[[events]]
type = "SEND_HEADERS"
id = 2



# Create request 3 (R2): GET the contents of `aaa.txt`.
[[events]]
type = "CREATE"
method = "GET"
uri = "files/aaa.txt"
id = 3

# Send entirety of R3.
[[events]]
type = "SEND_ALL"
id = 3

# Wait for R3 to complete.
[[events]]
type = "WAIT"
id = 3



# Create request 4 (R2): GET the contents of `bible.txt`.
[[events]]
type = "CREATE"
method = "GET"
uri = "files/bible.txt"
id = 4

# Send entirety of R4.
[[events]]
type = "SEND_ALL"
id = 4

# Wait for R4 to complete.
[[events]]
type = "WAIT"
id = 4




# Send R2's message body.
[[events]]
type = "SEND_BODY"
id = 2

# Wait for R2 to complete.
[[events]]
type = "WAIT"
id = 2





# Send R1's message body.
[[events]]
type = "SEND_BODY"
id = 1

# Wait for R1 to complete.
[[events]]
type = "WAIT"
id = 1

